package journal

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// 段2: 段1 の JSON **だけ**を入力に、claude CLI が文章を書く。
//
// 🛑 **LLM に数字を作らせない。** 入力は決定論パケットのみで、出力は文章のみ。
// 🛑 **発注経路の外**。何も arm せず、何も発注しない。判断にも使わない。

// プロンプトは**バイナリに焼く**。launchd は TCC 回避のため `~/.stockbot/bin/` の
// ビルド済みバイナリを repo 非依存で叩くので、相対パスのプロンプトはそこで必ず壊れる。
// 焼いておけば日記の再現性も上がる(どの規律で書かれたかが binary に固定される)。
//
//go:embed daily_review_prompt.md
var stage2Prompt string

// 🛑 **allowlist で渡す**。denylist だと、CLI にツールが増えるたびに黙って穴が開く
// (denylist 方式では Read / Glob / Grep / Artifact / Workflow が
// 子プロセスに残る。Artifact は日記を claude.ai へ公開できる経路)。
// 二重化は advisor と同じ規律(`--tools` を無視する CLI 版があっても素通りしない)。
var stage2ToolArgs = []string{"--tools", "WebSearch", "--allowed-tools", "WebSearch"}

// allowlist の二重化。CLI が `--tools` を無視しても、書込・実行系はここで落ちる。
const stage2DisallowedTools = "Bash,Edit,Write,NotebookEdit,Task,Read,Glob,Grep,Artifact,Workflow,Skill"

// 版番号を書かない(`opus` = 最新の Opus を指す CLI のエイリアス)。引け後なので
// 所要時間の制約が無く最大 effort でよい。
var stage2ModelArgs = []string{"--model", "opus", "--effort", "max"}

// buildStage2Prompt はプロンプト本文と当日パケットを結合する。**JSON をそのまま渡す**
// (要約しない)— 要約した時点で「LLM に数字を作らせない」が崩れる。
func buildStage2Prompt(promptBody string, packetJSON []byte) string {
	var b strings.Builder
	b.WriteString(promptBody)
	b.WriteString("\n\n## Input JSON\n\n```json\n")
	b.Write(packetJSON)
	b.WriteString("\n```\n")
	return b.String()
}

// cliEnvelope は `--output-format json` の返り。**どの世代が書いたか**を日記に焼くために
// 使う(advisor と同じ理由: `opus` の解決先は CLI のバージョンで変わる)。
// 🛑 世代は**トップレベルの `model` ではなく `modelUsage` のキー**に出る
// (advisor の splitEnvelope と同じ)。`model` だけを見ると
// 常に "unknown" を書き、provenance の目的を果たさない。
type cliEnvelope struct {
	Result     string                     `json:"result"`
	Model      string                     `json:"model"`
	ModelUsage map[string]json.RawMessage `json:"modelUsage"`
}

// envelopeModel は記録する世代名。map の反復順は不定なので sort して決定論にする。
func (e cliEnvelope) envelopeModel() string {
	if len(e.ModelUsage) == 0 {
		return e.Model
	}
	models := make([]string, 0, len(e.ModelUsage))
	for m := range e.ModelUsage {
		models = append(models, m)
	}
	sort.Strings(models)
	return strings.Join(models, ",")
}

// 総評と認める最低条件。プロンプトが「そのまま置く」と指定している警告文の一部で、
// **CLI が exit 0 で返した非総評テキスト**(usage limit 等)を日記として固定しないための杭。
// advisor が classifyCLIOutput で同じ罪を防いでいる。
const reviewMarker = "エッジの証拠ではない"

func RunStage2(ctx context.Context, cliPath, outDir, date string, packetJSON []byte, timeout time.Duration) (string, error) {
	out := filepath.Join(outDir, date+".md")
	args := append(append([]string{"-p", "--no-session-persistence"}, stage2ToolArgs...),
		append([]string{"--disallowed-tools", stage2DisallowedTools, "--output-format", "json"}, stage2ModelArgs...)...)
	cctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	cmd := exec.CommandContext(cctx, cliPath, args...)
	// 🛑 CWD を repo の外へ出す。CWD 配下は子プロセスから Read できてしまい(実測)、
	// 「JSON に無い数字を書かない」が道具レベルで支えられなくなる。日足 CSV も台帳の
	// md も repo 配下にある。
	cmd.Dir = os.TempDir()
	cmd.Stdin = strings.NewReader(buildStage2Prompt(stage2Prompt, packetJSON))
	var stderr strings.Builder
	cmd.Stderr = &stderr
	blob, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("claude CLI: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}
	text, model, err := stage2Text(blob)
	if err != nil {
		return "", err
	}
	// provenance: どの世代が書いたか。日記は月を跨いで読み比べる文書で、その間に CLI は上がる。
	body := fmt.Sprintf("<!-- generated by daily-review stage2 / model=%s -->\n%s\n", model, text)
	return out, writeExclusive(out, body)
}

// stage2Text は envelope から本文を取り出し、**総評として認めてよいか**を検査する。
func stage2Text(blob []byte) (text, model string, err error) {
	var env cliEnvelope
	if jerr := json.Unmarshal(blob, &env); jerr == nil && strings.TrimSpace(env.Result) != "" {
		text, model = strings.TrimSpace(env.Result), env.envelopeModel()
	} else {
		text = strings.TrimSpace(string(blob)) // envelope でなければ素のテキストとして扱う
	}
	if text == "" {
		return "", "", fmt.Errorf("claude CLI が空を返した — **空の総評を書かない**(欠測は欠測のまま残す)")
	}
	if !strings.Contains(text, reviewMarker) {
		// exit 0 でも usage limit / infra のメッセージが返ることがある(advisor の実測)。
		// append-only なので、それを書いた日は**二度と総評を書けなくなる**。
		return "", "", fmt.Errorf("総評の体をなしていない(冒頭の警告文が無い)。CLI の応答: %.200q", text)
	}
	if model == "" {
		model = "unknown"
	}
	return text, model, nil
}

// writeExclusive は **append-only をカーネルに保証させる**(O_EXCL)。stat → write だと
// TOCTOU で上書きに倒れる。書き換えを許すと「あの時こう思っていた」の後付けが効く。
func writeExclusive(path, body string) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if os.IsExist(err) {
		return fmt.Errorf("%s は既にある — 日記は append-only なので上書きしない(訂正はその日の追記として人間が書く)", path)
	}
	if err != nil {
		return err
	}
	if _, werr := f.WriteString(body); werr != nil {
		f.Close()
		os.Remove(path) // 途中で切れた .md を残すと、その日は二度と書けなくなる
		return werr
	}
	return f.Close()
}
