package main

import (
	"strings"
	"testing"
)

// 生成物は**決定論**でなければならない。map の反復順が漏れると、同じ入力から
// 毎回違う diff が出て「人間がレビューする生成物」として機能しなくなる。
func TestRenderIsDeterministic(t *testing.T) {
	in := renderInput{
		Fine:       []string{"7203", "9432", "1605"},
		PoolSize:   3,
		PoolDigest: "abc123",
		DerivedOn:  "2026-08-10",
		DataNote:   "test",
	}
	first := string(render(in))
	for i := 0; i < 20; i++ {
		if got := string(render(in)); got != first {
			t.Fatalf("render が実行ごとに変わる(%d 回目)", i)
		}
	}
}

// 銘柄コードは昇順で並ぶ(diff を人間が読めるようにするため)。
func TestRenderSortsSymbols(t *testing.T) {
	out := string(render(renderInput{Fine: []string{"9432", "1605", "7203"}, PoolDigest: "d"}))
	i1605 := strings.Index(out, `"1605"`)
	i7203 := strings.Index(out, `"7203"`)
	i9432 := strings.Index(out, `"9432"`)
	if i1605 < 0 || i7203 < 0 || i9432 < 0 {
		t.Fatalf("銘柄が出力に無い: %q", out)
	}
	if !(i1605 < i7203 && i7203 < i9432) {
		t.Errorf("昇順でない: 1605@%d 7203@%d 9432@%d", i1605, i7203, i9432)
	}
}

// digest と件数が生成物に焼かれること(ガードテストがこれを見てプールとの
// ずれを検出する)。
func TestRenderCarriesPoolProvenance(t *testing.T) {
	out := string(render(renderInput{Fine: []string{"7203"}, PoolSize: 1551, PoolDigest: "deadbeef", DerivedOn: "2026-08-10"}))
	for _, want := range []string{
		`FineTickPoolDigest = "deadbeef"`,
		`FineTickPoolSize = 1551`,
		`FineTickDerivedOn = "2026-08-10"`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("生成物に %q が無い", want)
		}
	}
}

// 生成物であることが一目で分かること(手で編集させないため)。
func TestRenderMarksGenerated(t *testing.T) {
	out := string(render(renderInput{Fine: []string{"7203"}, PoolDigest: "d"}))
	if !strings.Contains(out, "Code generated by cmd/tick-table") {
		t.Error("生成ヘッダが無い — 手編集を誘発する")
	}
	if !strings.HasPrefix(out, "// Code generated") {
		t.Error("生成ヘッダは先頭行でなければ go の慣行に沿わない")
	}
}

// プールが空、または細かい呼値が1件も出ないのは、データ未配置などの事故。
// 空のテーブルを黙って書くと**全銘柄が粗いテーブルへ倒れる**(今回直している
// バグそのもの)ので、生成側で fail-close する。
func TestValidateRefusesEmptyResult(t *testing.T) {
	if err := validate(renderInput{Fine: nil, PoolSize: 1551}); err == nil {
		t.Error("細かい呼値ゼロ件を通してはいけない(全銘柄が粗い側へ倒れる)")
	}
	if err := validate(renderInput{Fine: []string{"7203"}, PoolSize: 0}); err == nil {
		t.Error("プール0件を通してはいけない(allowed_symbols が読めていない)")
	}
	if err := validate(renderInput{Fine: []string{"7203"}, PoolSize: 1551}); err != nil {
		t.Errorf("正常な入力を弾いた: %v", err)
	}
}

// digest はプール(allowed_symbols)だけで決まり、順序に依存しない。
func TestPoolDigestIsOrderIndependent(t *testing.T) {
	a := poolDigest([]string{"7203", "9432", "1605"})
	b := poolDigest([]string{"1605", "7203", "9432"})
	if a != b {
		t.Errorf("順序で digest が変わる: %s != %s", a, b)
	}
	if c := poolDigest([]string{"7203", "9432"}); c == a {
		t.Error("プールが変われば digest も変わるべき")
	}
}
