package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// renderInput は生成物に焼く内容。
type renderInput struct {
	Fine       []string // 細かい呼値と**判定できた**銘柄(証拠あり)
	PoolSize   int      // 走査した allowed_symbols の件数
	PoolDigest string   // 同プールの digest(ガードテストが照合する)
	DerivedOn  string   // 導出日(YYYY-MM-DD)
	DataNote   string   // 由来データの説明(再現用)
}

// poolDigest は allowed_symbols の内容だけで決まる指紋。順序非依存。
// プールが変わったのにテーブルを再生成していない、を検出するために使う。
func poolDigest(pool []string) string {
	s := append([]string(nil), pool...)
	sort.Strings(s)
	h := sha256.Sum256([]byte(strings.Join(s, ",")))
	return hex.EncodeToString(h[:])[:16]
}

// validate は「黙って壊れた生成物を書く」のを防ぐ fail-close。
func validate(in renderInput) error {
	if in.PoolSize == 0 {
		return fmt.Errorf("プールが0件 — allowed_symbols を読めていない")
	}
	if len(in.Fine) == 0 {
		return fmt.Errorf("細かい呼値の銘柄が0件 — 日足CSVが見つかっていない可能性が高い" +
			"(空テーブルを書くと全銘柄が粗いテーブルへ倒れ、執行コストが最大10倍で記録される)")
	}
	return nil
}

func render(in renderInput) []byte {
	syms := append([]string(nil), in.Fine...)
	sort.Strings(syms)

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by cmd/tick-table. DO NOT EDIT.
//
// 東証の呼値の単位は銘柄で2種類あり、どちらを引くかで TP/SL の位置と紙執行の
// コストが 2〜10倍ずれる(tick_fine.go)。この表は**手で並べない** — プール
// (hard_limits.allowed_symbols)の全銘柄について、実際の約定値が粗いグリッドに
// 乗らないことを証拠として market.InferTickRegime が判定した結果である。
//
// 手で並べていた頃は表が旧ユニバースしか覆っておらず、日次ユニバースが銘柄を
// 入れ替えるたびに穴が空いた(新規採用46銘柄が全て未収録で、うち
// 37銘柄は実価格が粗い刻みに乗っていない=明確な誤り。往復コスト中央値が継続
// 銘柄 8.4bps に対し 50.6bps と 6倍になり、測ろうとしているエッジ(+3,879円/
// 本・¥1M正規化)より歪みの方が大きい状態だった)。
//
// 再生成: go run ./cmd/tick-table -allow-file ../configs/hard_limits.yaml (プール変更 / データ更新のたび。人間が diff を読む)
//
//	導出日   : %s
//	由来     : %s
//	プール   : %d 銘柄 (digest %s)
//	細かい呼値: %d 銘柄 (残りは証拠なし = 粗いテーブル。fail-safe 側)
package market

// FineTickDerivedOn はこの表を導出した日。
const FineTickDerivedOn = %q

// FineTickPoolSize / FineTickPoolDigest は導出時に走査した allowed_symbols。
// プールを増減したのに再生成していないと config 側のガードテストが落ちる。
const FineTickPoolSize = %d

// FineTickPoolDigest は allowed_symbols の順序非依存な指紋。
const FineTickPoolDigest = %q

var fineTickSymbols = map[string]struct{}{
`, in.DerivedOn, in.DataNote, in.PoolSize, in.PoolDigest, len(syms), in.DerivedOn, in.PoolSize, in.PoolDigest)

	const perLine = 8
	for i, s := range syms {
		if i%perLine == 0 {
			b.WriteString("\t")
		}
		fmt.Fprintf(&b, "%q: {},", s)
		if i%perLine == perLine-1 || i == len(syms)-1 {
			b.WriteString("\n")
		} else {
			b.WriteString(" ")
		}
	}
	b.WriteString("}\n")
	return b.Bytes()
}
